### PR TITLE
Adding check for exp to be ready and preview

### PR DESCRIPTION
**Pull request by hemkaran**
Hi,

Segment is doing wrong tracking as it not checking for experiment to be ready. Also, it is sending data in VWO preview mode also.

### CODE REVIEW

**Comment by WesleyDRobinson** [comment]
👁 @hankim813 @tsholmes for review

**Comment by hankim813** [comment]
@hemkaran thanks for the PR! Could you add a unit test for the new `if` guard? 

Also looks like circle failed due to lint errors

**Comment by hemkaran** [comment]
@hankim813 Can you please review now?

**Review by hankim813 — APPROVED** [review]
lgtm! can you just add a release commit?

bump `package.json` version 
and update HISTORY.md
`$ git commit -m 'Release x.x.x'

thanks so much!

**Comment by hemkaran** [comment]
@hankim813 Can you please release it? One VWO client is waiting for the fix.

**Comment by hankim813** [comment]
@hemkaran deployed! thanks for the PR!

**Comment by hemkaran** [comment]
@hankim813 Thanks. Checked it, working perfectly fine.

**Pull request merged**
